const { v4: uuidv4 } = require('uuid');
const logger = require('../utils/logger');
const scannerModule = require('./arbitrage-scanner.service');
const alertService = require('./alert.service');
const scannerAlertSettingsService = require('./scanner-alert-settings.service');

const DEMO_MODE = process.env.DEMO_MODE === 'true';

/**
 * Scanner scheduler service.
 * In demo mode it generates synthetic alerts and does not require external APIs.
 */
class SchedulerService {
    constructor() {
        this.tasks = new Map();
        this.alertCallbacks = [];
        this.nextRunByTenant = new Map();

        this.config = {
            enabled: process.env.SCANNER_ENABLED !== 'false',
            configRefreshSeconds: Math.max(3, parseInt(process.env.SCANNER_ALERTS_CONFIG_REFRESH_SECONDS, 10) || 10),
            testingMode: process.env.SCANNER_TESTING_MODE !== 'false',
            timezone: 'Europe/Moscow',
        };

        this.isInitialized = false;
        this.scanInProgress = false;
    }

    async initialize() {
        if (this.isInitialized) {
            logger.warn('Scheduler already initialized');
            return;
        }

        if (!this.config.enabled) {
            logger.info('Scheduler disabled by configuration');
            return;
        }

        await scannerAlertSettingsService.initialize();

        if (DEMO_MODE) {
            logger.info('Scheduler initialized in DEMO mode (mock alerts)', {
                configRefreshSeconds: this.config.configRefreshSeconds,
                timezone: this.config.timezone,
            });

            const intervalMs = this.config.configRefreshSeconds * 1000;
            const interval = setInterval(async () => {
                try {
                    await this.runScheduledScans();
                } catch (error) {
                    logger.error('Demo scheduler run failed', { error: error.message });
                }
            }, intervalMs);

            this.tasks.set('demo-run', {
                interval,
                intervalMs,
                nextRun: new Date(Date.now() + intervalMs),
            });

            this.isInitialized = true;
            return;
        }

        logger.info('Scheduler initialized in production mode', {
            configRefreshSeconds: this.config.configRefreshSeconds,
        });

        this.scheduleIntervalTask(
            'settings-poll',
            this.config.configRefreshSeconds / 60,
            async () => {
                await this.runScheduledScans();
            },
            this.config.configRefreshSeconds * 1000
        );

        this.isInitialized = true;
    }

    scheduleIntervalTask(name, intervalMinutes, callback, firstRunDelayMs = 1000) {
        const intervalMs = intervalMinutes * 60 * 1000;

        const firstRunTimeout = setTimeout(async () => {
            try {
                await callback();
            } catch (error) {
                logger.error(`Scheduler task ${name} failed`, { error: error.message });
            }
        }, firstRunDelayMs);

        const interval = setInterval(async () => {
            try {
                await callback();
            } catch (error) {
                logger.error(`Scheduler task ${name} failed`, { error: error.message });
            }
        }, intervalMs);

        this.tasks.set(name, {
            interval,
            firstRunTimeout,
            intervalMinutes,
            intervalMs,
            nextRun: new Date(Date.now() + firstRunDelayMs),
        });
    }

    scheduleDailyTask(name, hour, minute, callback) {
        const getNextRunTime = () => {
            const now = new Date();
            const next = new Date();
            next.setHours(hour, minute, 0, 0);

            if (next <= now) {
                next.setDate(next.getDate() + 1);
            }

            return next.getTime() - now.getTime();
        };

        const scheduleNext = () => {
            const msUntilNext = getNextRunTime();
            const nextRun = new Date(Date.now() + msUntilNext);

            const timeout = setTimeout(async () => {
                try {
                    await callback();
                } catch (error) {
                    logger.error(`Scheduler task ${name} failed`, { error: error.message });
                }
                scheduleNext();
            }, msUntilNext);

            this.tasks.set(name, {
                timeout,
                nextRun,
                hour,
                minute,
            });
        };

        scheduleNext();
    }

    _buildMockAlert(tenantId, source = 'scheduler') {
        return {
            id: uuidv4(),
            type: 'scanner_alert',
            tenantId,
            message: `Demo scanner alert generated by ${source}`,
            timestamp: new Date().toISOString(),
            data: {
                severity: 'medium',
                triggerType: 'mock-scan',
                generatedInDemo: true,
                content: 'Synthetic alert for public demo.',
            },
        };
    }

    async runScheduledScans() {
        if (this.scanInProgress) {
            return { status: 'skipped', reason: 'Scan already in progress' };
        }

        this.scanInProgress = true;
        const tenants = scannerModule.getConfiguredTenants();
        const nowTs = Date.now();
        const results = {};

        try {
            for (const tenantId of tenants) {
                try {
                    const settings = await scannerAlertSettingsService.getSettings(tenantId);
                    const activeLists = this._getActiveLists(settings);

                    if (!settings.scanner_enabled) {
                        await scannerAlertSettingsService.updateRuntimeStatus(tenantId, {
                            worker_alive: true,
                            last_run_status: 'disabled',
                            next_run_at: null,
                            interval_seconds: settings.interval_seconds,
                            active_lists: activeLists,
                            last_error: null,
                        });
                        results[tenantId] = { status: 'disabled' };
                        continue;
                    }

                    if (!activeLists.length) {
                        await scannerAlertSettingsService.updateRuntimeStatus(tenantId, {
                            worker_alive: true,
                            last_run_status: 'no_active_lists',
                            next_run_at: null,
                            interval_seconds: settings.interval_seconds,
                            active_lists: [],
                            last_error: null,
                        });
                        results[tenantId] = { status: 'no_active_lists' };
                        continue;
                    }

                    if (DEMO_MODE) {
                        const nextRunTs = this.nextRunByTenant.get(tenantId) || nowTs;
                        if (nowTs < nextRunTs) {
                            await scannerAlertSettingsService.updateRuntimeStatus(tenantId, {
                                worker_alive: true,
                                next_run_at: new Date(nextRunTs).toISOString(),
                                interval_seconds: settings.interval_seconds,
                                active_lists: activeLists,
                                last_error: null,
                            });
                            results[tenantId] = {
                                status: 'waiting',
                                next_run_at: new Date(nextRunTs).toISOString(),
                            };
                            continue;
                        }

                        const runResult = await this.runScanForTenant(tenantId, {
                            trigger: 'scheduled',
                            settings,
                        });

                        const nextRunAtTs = Date.now() + (settings.interval_seconds * 1000);
                        this.nextRunByTenant.set(tenantId, nextRunAtTs);

                        await scannerAlertSettingsService.updateRuntimeStatus(tenantId, {
                            worker_alive: true,
                            last_run_at: new Date().toISOString(),
                            next_run_at: new Date(nextRunAtTs).toISOString(),
                            last_run_status: runResult.status === 'completed' ? 'success' : runResult.status,
                            interval_seconds: settings.interval_seconds,
                            active_lists: activeLists,
                            last_error: runResult.error || null,
                        });

                        results[tenantId] = runResult;
                        continue;
                    }

                    const runResult = await this.runScanForTenant(tenantId, {
                        trigger: 'scheduled',
                        settings,
                    });

                    await scannerAlertSettingsService.updateRuntimeStatus(tenantId, {
                        worker_alive: true,
                        last_run_at: new Date().toISOString(),
                        last_run_status: runResult.status,
                        interval_seconds: settings.interval_seconds,
                        active_lists: activeLists,
                        last_error: runResult.error || null,
                    });

                    results[tenantId] = runResult;
                } catch (error) {
                    logger.error(`Scheduler failed for tenant ${tenantId}`, { error: error.message });
                    await scannerAlertSettingsService.updateRuntimeStatus(tenantId, {
                        worker_alive: true,
                        last_run_status: 'error',
                        last_error: error.message,
                    });
                    results[tenantId] = { status: 'error', error: error.message };
                }
            }

            return { status: 'completed', results };
        } finally {
            this.scanInProgress = false;
        }
    }

    _getActiveLists(settings) {
        return this.getAvailableLists(settings);
    }

    getAvailableLists(settings) {
        return [
            settings.lists?.top_winners,
            settings.lists?.top_by_trade_count,
            settings.lists?.new_accounts,
        ].map((value, index) => ({
            key: ['top_winners', 'top_by_trade_count', 'new_accounts'][index],
            enabled: value,
        })).filter((item) => item.enabled).map((item) => item.key);
    }

    async runAllTenantScans() {
        if (this.scanInProgress) {
            logger.warn('Scheduler: scan already in progress, skipping all-tenant run');
            return { status: 'skipped', reason: 'Scan already in progress' };
        }

        this.scanInProgress = true;
        const tenants = scannerModule.getConfiguredTenants();
        const results = {};

        try {
            for (const tenantId of tenants) {
                try {
                    results[tenantId] = await this.runScanForTenant(tenantId, { force: true, trigger: 'manual' });
                    await new Promise((resolve) => setTimeout(resolve, 100));
                } catch (error) {
                    results[tenantId] = { status: 'error', error: error.message };
                }
            }

            return { status: 'completed', results };
        } finally {
            this.scanInProgress = false;
        }
    }

    async _runDemoScan(tenantId, options = {}, settings = null) {
        const baseSettings = settings || await scannerAlertSettingsService.getSettings(tenantId);
        const alerts = [];

        if (!baseSettings.scanner_enabled) {
            return { status: 'disabled', tenantId };
        }

        const activeLists = this._getActiveLists(baseSettings);
        if (activeLists.length === 0) {
            return { status: 'no_active_lists', tenantId, active_lists: activeLists };
        }

        if (options.force || activeLists.length > 0) {
            const alert = this._buildMockAlert(tenantId, options.trigger || 'manual');
            alerts.push(alert);
            alertService.queueAlerts([alert]);
            for (const callback of this.alertCallbacks) {
                try {
                    await callback([alert], tenantId);
                } catch (error) {
                    logger.error('Demo alert callback failed', { error: error.message });
                }
            }
        }

        return {
            status: 'completed',
            tenantId,
            alertCount: alerts.length,
            alerts: alerts.map((alert) => ({ id: alert.id, tenantId: alert.tenantId })),
            active_lists: activeLists,
        };
    }

    async runScanForTenant(tenantId = 'default', options = {}) {
        const settings = await scannerAlertSettingsService.getSettings(tenantId);

        if (DEMO_MODE) {
            return this._runDemoScan(tenantId, options, settings);
        }

        const scanner = scannerModule.getScanner(tenantId);
        scanner.applyRuntimeSettings(settings);

        if (!options.force && settings.scanner_enabled === false) {
            return {
                status: 'disabled',
                tenantId,
                reason: 'Scanner alerts are disabled',
            };
        }

        const result = await scanner.runScan();

        if (result.status === 'completed') {
            if (result.alert) {
                alertService.queueAlerts([result.alert]);
            }

            if (result.alerts && result.alerts.length > 0) {
                for (const callback of this.alertCallbacks) {
                    try {
                        await callback(result.alerts, tenantId);
                    } catch (error) {
                        logger.error('Scheduler alert callback failed', { error: error.message });
                    }
                }
            }
        }

        return result;
    }

    async runArbitrageScan(tenantId = 'default') {
        return this.runScanForTenant(tenantId);
    }

    onNewAlerts(callback) {
        this.alertCallbacks.push(callback);
        logger.info('Scheduler: alert callback registered');
    }

    async triggerScan(tenantId = null) {
        if (tenantId) {
            logger.info(`Scheduler: manual scan requested for tenant ${tenantId}`);
            return await this.runScanForTenant(tenantId, { force: true, trigger: 'manual' });
        }

        logger.info('Scheduler: manual scan requested for all tenants');
        return await this.runAllTenantScans();
    }

    getStatus() {
        const tenants = scannerModule.getConfiguredTenants();
        const taskStatuses = {};

        for (const [name, task] of this.tasks.entries()) {
            taskStatuses[name] = {
                nextRun: task.nextRun ? task.nextRun.toISOString() : null,
                scheduledTime: Number.isInteger(task.hour) ? `${task.hour}:${String(task.minute).padStart(2, '0')}` : null,
                intervalMinutes: task.intervalMinutes || null,
            };
        }

        const tenantStatuses = {};
        for (const tenantId of tenants) {
            const scanner = scannerModule.getScanner?.(tenantId);
            tenantStatuses[tenantId] = this._getTenantStatusFromScanner(scanner, tenantId);
        }

        return {
            enabled: this.config.enabled,
            initialized: this.isInitialized,
            scanInProgress: this.scanInProgress,
            mode: DEMO_MODE ? 'demo' : 'production',
            tasks: taskStatuses,
            alertCallbacksCount: this.alertCallbacks.length,
            configuredTenants: tenants,
            tenantStatuses,
            alertStats: alertService.getStats(),
        };
    }

    _getTenantStatusFromScanner(scanner, tenantId) {
        return scanner
            ? {
                  tenantId,
                  scannerExists: true,
                  lastScanTime: scanner.lastScanTime,
                  isRunning: scanner.isRunning,
                  nextRunAt: this.nextRunByTenant.get(tenantId)
                      ? new Date(this.nextRunByTenant.get(tenantId)).toISOString()
                      : null,
              }
            : {
                  tenantId,
                  scannerExists: false,
                  nextRunAt: this.nextRunByTenant.get(tenantId)
                      ? new Date(this.nextRunByTenant.get(tenantId)).toISOString()
                      : null,
              };
    }

    stop() {
        for (const task of this.tasks.values()) {
            if (task.timeout) {
                clearTimeout(task.timeout);
            }
            if (task.interval) {
                clearInterval(task.interval);
            }
            if (task.firstRunTimeout) {
                clearTimeout(task.firstRunTimeout);
            }
        }

        this.tasks.clear();
        this.nextRunByTenant.clear();
        this.isInitialized = false;
    }
}

module.exports = new SchedulerService();
